//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_interaction_framework : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Teleport
        {
            get
            {
                return SteamVR_Actions.interaction_framework_Teleport;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.interaction_framework_Pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean InteractUI
        {
            get
            {
                return SteamVR_Actions.interaction_framework_InteractUI;
            }
        }
        
        public virtual SteamVR_Action_Boolean Grab
        {
            get
            {
                return SteamVR_Actions.interaction_framework_Grab;
            }
        }
        
        public virtual SteamVR_Action_Boolean Use
        {
            get
            {
                return SteamVR_Actions.interaction_framework_Use;
            }
        }
        
        public virtual SteamVR_Action_Vector2 TouchpadPos
        {
            get
            {
                return SteamVR_Actions.interaction_framework_TouchpadPos;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.interaction_framework_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Boolean LaserPointer
        {
            get
            {
                return SteamVR_Actions.interaction_framework_LaserPointer;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.interaction_framework_Haptic;
            }
        }
    }
}
